# vim ft=yaml
# travis-ci.org definition for nipy build
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
language: erlang
env:
    - PYTHON=python PYSUF=''
    # - PYTHON=python3 PYSUF=3 : python3-numpy not currently available
install:
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-networkx
    - sudo apt-get install $PYTHON-traits
    - sudo apt-get install $PYTHON-setuptools
    - sudo easy_install$PYSUF nibabel # Latest pypi
    - sudo apt-get install $PYTHON-nose
script:
    # Change into an innocuous directory and find tests from installation
    - make test
